### ISSUE TITLE
import resolver not working as expected

### ISSUE THREAD

**Issue by 7iomka** [webmakaka/React-hooks-writing-real-project#2]
Привет

В начале курса ты показываешь подход в котором для резолва абсолютных "альясных" путей ты юзал вложение в node_modules внутри src.
Такой подход является антипаттерном, так как вызывает проблемы с интеграцией работы таких плагинов как prettier которые по дефолту игнорят node_modules на любых уровнях и пофиксить это невозможно.
В финальной версии проекта я вижу что папки с node_modules нету
но ты юзаешь конструкцию
```
"import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
```

которая должна работать (и обычно работает если юзают алиасы типа @, ~, но там доп. конфиг вебпака нужно указывать)
По итогу при запуске проекта я наблюдаю такую ошибку.
Подскажи в чем проблема плиз)
Спасибо)
![image](https://user-images.githubusercontent.com/18473137/76868385-7dd52280-686f-11ea-9147-f1f4dacec81f.png)

**Comment by webmakaka** [comment]
Привет! 

Курс не мой, я сам только начал осваивать Hooks.
Писать свой код в mode_modules, какое-то странное и с моей точки зрения глупое решение автора. Мало того, что сам херню какую-то придумал, так еще и кучу народа научит так делать.

В общем код моего финального проекта не работал, из-за отсутствия файла **.env**. А отсутствовал он из-за настроек игнора в **.gitignore** и соответственно файл не попал в репо. 
Сейчас добавил, все заработало. Спасибо, что нашел ошибку.

Если смотришь курсы по js, особенно react/node, добавляйся к нам в телеграм. 
https://t.me/jsdev_ru

**Comment by 7iomka** [comment]
@webmakaka , Я сам на реакте пробовал писать достаточно давно, сейчас хочу пощупать его и вижу что с хуками он вообще преобразился до неузнаваемости, вот и решил посмотреть курс какой-нибудь на русском, а то абстракционного понимания на английском языке у меня достаточно в других сферах)
Думал что ты автор курса))
Насчёт issue, я сам допёр до этого путём проб и ошибок, гуглением понял что последняя версия cra поддерживает абсолютные пути из коробки, требуется лишь немного настроек.

У меня также не завёлся prettier + eslint как нужно. Это больная тема со времен моего вхождения в фронтенд, всё притянуто за уши относительно редактора которого юзаешь.
Я юзаю vscode, его таки получилось настроить "как надо"

Вот моя ветка (дошёл пока до 7-ого урока)
https://github.com/7iomka/medium_clone/

В группу добавился)
Issue можно закрывать)
